/**
 * Suite runner + stability gate (shared by playwright-web and playwright-electron).
 *
 * Materializes a `playwright.config.ts` in the workdir, runs the generated specs
 * `runs` times each via the Playwright test runner with the JSON reporter, and
 * classifies every spec as pass / fail / flaky. A spec is ACCEPTED only if all
 * of its runs pass; mixed results are quarantined (PRD §5.4).
 */

import { writeFileSync, readFileSync, symlinkSync, existsSync } from 'node:fs';
import { basename, dirname, join, sep } from 'node:path';
import { createRequire } from 'node:module';
import type {
  ExecOpts,
  ExecutionResult,
  GeneratedTest,
  Logger,
  SingleRun,
  TestRunResult,
} from '../adapter.js';
import { runCommand } from '../../core/llm/spawn.js';

export interface RunnerOptions {
  /** baseURL for web targets; omit for electron (specs self-launch). */
  baseURL?: string;
  /** Persisted session to inject (web). */
  storageStatePath?: string;
  logger: Logger;
}

/** Resolve the Playwright `test` CLI shipped with this package (no network).
 *  cli.js is not in the package `exports`, so resolve via package.json. */
function resolvePlaywrightCli(): string {
  const require = createRequire(import.meta.url);
  for (const pkg of ['playwright', '@playwright/test']) {
    try {
      const pkgJson = require.resolve(`${pkg}/package.json`);
      const cli = join(dirname(pkgJson), 'cli.js');
      if (existsSync(cli)) return cli;
    } catch {
      /* try next */
    }
  }
  throw new Error(
    'Could not locate the Playwright CLI. Run `npm install` and `npx playwright install` first.',
  );
}

/** The node_modules dir containing a resolved CLI path. */
function nodeModulesDirOf(cliPath: string): string | undefined {
  const marker = `${sep}node_modules${sep}`;
  const idx = cliPath.lastIndexOf(marker);
  return idx >= 0 ? cliPath.slice(0, idx + marker.length - 1) : undefined;
}

/** Walk up from startDir until a node_modules dir is found. */
function findNodeModulesAbove(startDir: string): string | undefined {
  let dir = startDir;
  for (let i = 0; i < 8; i++) {
    const nm = join(dir, 'node_modules');
    if (existsSync(nm)) return nm;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

/** Ensure generated specs (which may live outside this package's tree, e.g. a
 *  user repo or /tmp) can resolve `@playwright/test` by linking node_modules. */
function ensureModuleResolution(workdir: string, nodeModulesDir: string | undefined): void {
  if (!nodeModulesDir) return;
  const link = join(workdir, 'node_modules');
  if (existsSync(link)) return;
  try {
    symlinkSync(nodeModulesDir, link, 'dir');
  } catch {
    /* fall back to NODE_PATH (set on the spawn env) */
  }
}

function writeConfig(workdir: string, opts: RunnerOptions, execOpts: ExecOpts): string {
  const use: Record<string, unknown> = {
    headless: !execOpts.headed,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  };
  if (opts.baseURL) use.baseURL = opts.baseURL;
  if (opts.storageStatePath) use.storageState = opts.storageStatePath;

  // When specs live in an external outputDir (e.g. lhappautotest), set testDir
  // to that absolute path; otherwise default to '.' (workdir).
  const testDir = execOpts.outputDir ? JSON.stringify(execOpts.outputDir) : "'.'";

  const config = `// AUTO-GENERATED by aidlc-testagent for the stability run. Safe to delete.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: ${testDir},
  testIgnore: ['**/node_modules/**'],
  fullyParallel: false,
  workers: 1,
  timeout: ${execOpts.timeoutMs},
  reporter: [['json', { outputFile: ${JSON.stringify(reportPath(workdir))} }]],
  use: ${JSON.stringify(use, null, 2)},
});
`;
  const configPath = join(workdir, 'playwright.config.ts');
  writeFileSync(configPath, config, 'utf8');
  return configPath;
}

/** Absolute path the JSON reporter writes to — read from a file, not stdout
 *  (stdout can be empty/polluted, and is lost if the process is killed). */
function reportPath(workdir: string): string {
  return join(workdir, '.pw-report.json');
}

interface JsonResult {
  status?: string;
  duration?: number;
  error?: { message?: string };
  errors?: { message?: string }[];
}
interface JsonTest {
  results?: JsonResult[];
  status?: string;
}
interface JsonSpec {
  title?: string;
  file?: string;
  ok?: boolean;
  tests?: JsonTest[];
}
interface JsonSuite {
  file?: string;
  suites?: JsonSuite[];
  specs?: JsonSpec[];
}
interface JsonReport {
  suites?: JsonSuite[];
  errors?: { message?: string }[];
}

function collectSpecs(suites: JsonSuite[] | undefined, acc: JsonSpec[] = []): JsonSpec[] {
  for (const s of suites ?? []) {
    for (const spec of s.specs ?? []) acc.push(spec);
    if (s.suites) collectSpecs(s.suites, acc);
  }
  return acc;
}

/** Run the suite through the stability gate and classify each test. */
export async function runStabilitySuite(
  tests: GeneratedTest[],
  execOpts: ExecOpts,
  opts: RunnerOptions,
): Promise<ExecutionResult> {
  const { logger } = opts;
  const cli = resolvePlaywrightCli();

  let nodeModulesDir: string | undefined;
  if (execOpts.outputDir) {
    // Specs live in an external repo (e.g. lhappautotest). Use that repo's own
    // node_modules for resolution — don't symlink aidlc-testagent's into workdir.
    nodeModulesDir = findNodeModulesAbove(execOpts.outputDir);
  } else {
    nodeModulesDir = nodeModulesDirOf(cli);
    ensureModuleResolution(execOpts.workdir, nodeModulesDir);
  }

  const configPath = writeConfig(execOpts.workdir, opts, execOpts);

  const args = [
    cli,
    'test',
    '--config',
    configPath,
    '--repeat-each',
    String(execOpts.runs),
    '--reporter=json',
  ];

  logger.debug(`Running: node ${args.join(' ')} (cwd ${execOpts.workdir})`);
  const res = await runCommand('node', args, {
    cwd: execOpts.workdir,
    timeoutMs: Math.max(60_000, execOpts.timeoutMs * execOpts.runs * tests.length + 60_000),
    env: {
      FORCE_COLOR: '0',
      ...(nodeModulesDir ? { NODE_PATH: nodeModulesDir } : {}),
    },
    // Strip ELECTRON_RUN_AS_NODE so specs that call _electron.launch() (both
    // directly and via lhappautotest fixtures) don't inherit it from Claude Code.
    omitEnv: ['ELECTRON_RUN_AS_NODE', 'ELECTRON_NO_ATTACH_CONSOLE'],
  });

  const reportFile = reportPath(execOpts.workdir);
  let report: JsonReport;
  try {
    const raw = existsSync(reportFile) ? readFileSync(reportFile, 'utf8') : res.stdout;
    report = JSON.parse(extractJson(raw)) as JsonReport;
  } catch {
    const killed = res.timedOut ? ' (runner timed out)' : res.signal ? ` (killed: ${res.signal})` : '';
    throw new Error(
      `Could not read Playwright JSON report${killed} (exit ${res.code}). ` +
        `Expected ${reportFile}.\nstderr: ${res.stderr.slice(0, 800) || '(empty)'}\nstdout: ${res.stdout.slice(0, 400) || '(empty)'}`,
    );
  }

  const specs = collectSpecs(report.suites);

  const passed: TestRunResult[] = [];
  const failed: TestRunResult[] = [];
  const quarantined: TestRunResult[] = [];

  for (const test of tests) {
    const matching = specs.filter((sp) => sameFile(sp.file, test.filePath));
    const results: JsonResult[] = matching.flatMap((sp) => (sp.tests ?? []).flatMap((t) => t.results ?? []));

    const runs: SingleRun[] = results.map((r, i) => ({
      index: i,
      ok: r.status === 'passed' || r.status === 'expected',
      durationMs: r.duration,
      error: r.error?.message ?? r.errors?.[0]?.message,
    }));

    // No results matched (e.g. compile error) → treat as a failure.
    if (runs.length === 0) {
      failed.push({
        test,
        runs: [{ index: 0, ok: false, error: 'no run results (compile error or no test found in spec)' }],
        status: 'fail',
        error: report.errors?.[0]?.message ?? 'spec did not run',
      });
      continue;
    }

    const okCount = runs.filter((r) => r.ok).length;
    const firstError = runs.find((r) => !r.ok)?.error;
    if (okCount === runs.length) {
      passed.push({ test, runs, status: 'pass' });
    } else if (okCount === 0) {
      failed.push({ test, runs, status: 'fail', error: firstError });
    } else {
      quarantined.push({ test, runs, status: 'flaky', error: firstError });
    }
  }

  return {
    passed,
    failed,
    quarantined,
    total: tests.length,
    artifactsDir: join(execOpts.workdir, 'test-results'),
  };
}

function sameFile(reportFile: string | undefined, relPath: string): boolean {
  if (!reportFile) return false;
  const a = reportFile.replace(/\\/g, '/');
  const b = relPath.replace(/\\/g, '/');
  return a === b || a.endsWith(b) || basename(a) === basename(b);
}

function extractJson(text: string): string {
  const t = text.trim();
  const start = t.indexOf('{');
  const end = t.lastIndexOf('}');
  return start >= 0 && end > start ? t.slice(start, end + 1) : t;
}
